version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload