[project]
name = "pdf-highlight-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pymupdf>=1.26.4",
    "python-multipart>=0.0.20",
    "uvicorn>=0.35.0",
]
